local frame = require("claude-transport.server.frame")
local utils = require("claude-transport.server.utils")

describe("WebSocket frame", function()
	describe("create and parse round-trip", function()
		it("round-trips text frame", function()
			local text = "Hello, World!"
			local data = frame.create_text_frame(text)
			local parsed, consumed = frame.parse_frame(data)
			assert.is_not_nil(parsed)
			assert.equals(frame.OPCODE.TEXT, parsed.opcode)
			assert.equals(text, parsed.payload)
			assert.is_true(parsed.fin)
		end)

		it("round-trips binary frame", function()
			local binary = "\x00\x01\x02\x03"
			local data = frame.create_binary_frame(binary)
			local parsed, consumed = frame.parse_frame(data)
			assert.is_not_nil(parsed)
			assert.equals(frame.OPCODE.BINARY, parsed.opcode)
			assert.equals(binary, parsed.payload)
		end)

		it("round-trips ping frame", function()
			local data = frame.create_ping_frame("ping-data")
			local parsed, consumed = frame.parse_frame(data)
			assert.is_not_nil(parsed)
			assert.equals(frame.OPCODE.PING, parsed.opcode)
			assert.equals("ping-data", parsed.payload)
		end)

		it("round-trips pong frame", function()
			local data = frame.create_pong_frame("pong-data")
			local parsed, consumed = frame.parse_frame(data)
			assert.is_not_nil(parsed)
			assert.equals(frame.OPCODE.PONG, parsed.opcode)
			assert.equals("pong-data", parsed.payload)
		end)

		it("round-trips close frame", function()
			local data = frame.create_close_frame(1000, "normal")
			local parsed, consumed = frame.parse_frame(data)
			assert.is_not_nil(parsed)
			assert.equals(frame.OPCODE.CLOSE, parsed.opcode)
		end)
	end)

	describe("create_frame", function()
		it("creates unmasked frame by default", function()
			local data = frame.create_text_frame("test")
			local parsed, _ = frame.parse_frame(data)
			assert.is_false(parsed.masked)
		end)

		it("creates masked frame when requested", function()
			local data = frame.create_frame(frame.OPCODE.TEXT, "test", true, true)
			local b2 = data:byte(2)
			local masked = math.floor(b2 / 128) == 1
			assert.is_true(masked)
		end)
	end)

	describe("parse_frame edge cases", function()
		it("returns nil for empty data", function()
			local parsed, consumed = frame.parse_frame("")
			assert.is_nil(parsed)
			assert.equals(0, consumed)
		end)

		it("returns nil for single byte", function()
			local parsed, consumed = frame.parse_frame("\x81")
			assert.is_nil(parsed)
			assert.equals(0, consumed)
		end)

		it("returns nil for non-string input", function()
			local parsed, consumed = frame.parse_frame(42)
			assert.is_nil(parsed)
			assert.equals(0, consumed)
		end)

		it("handles zero-length text payload", function()
			local data = frame.create_text_frame("")
			local parsed, consumed = frame.parse_frame(data)
			assert.is_not_nil(parsed)
			assert.equals("", parsed.payload)
			assert.equals(0, parsed.payload_length)
		end)

		it("rejects invalid UTF-8 in text frames", function()
			local payload = "\xC0\x00"
			local b1 = string.char(128 + frame.OPCODE.TEXT)
			local b2 = string.char(#payload)
			local data = b1 .. b2 .. payload
			local parsed, consumed = frame.parse_frame(data)
			assert.is_nil(parsed)
		end)
	end)

	describe("parse_frame error signaling", function()
		it("reports incomplete (no error) for a truncated valid frame", function()
			local full = frame.create_frame(frame.OPCODE.TEXT, "hello world", true, true)
			local partial = full:sub(1, #full - 3)
			local parsed, consumed, err = frame.parse_frame(partial)
			assert.is_nil(parsed)
			assert.equals(0, consumed)
			assert.is_nil(err)
		end)

		it("reports a protocol error when reserved bits are set", function()
			local data = string.char(0xC1) .. string.char(0x80) .. "\0\0\0\0"
			local parsed, consumed, err = frame.parse_frame(data)
			assert.is_nil(parsed)
			assert.equals(0, consumed)
			assert.is_string(err)
		end)

		it("reports a protocol error for an invalid opcode", function()
			local data = string.char(0x83) .. string.char(0x80) .. "\0\0\0\0"
			local parsed, consumed, err = frame.parse_frame(data)
			assert.is_nil(parsed)
			assert.equals(0, consumed)
			assert.is_string(err)
		end)

		it("reports a protocol error for an over-long control frame", function()
			local data = string.char(0x88) .. string.char(0xFE)
			local parsed, consumed, err = frame.parse_frame(data)
			assert.is_nil(parsed)
			assert.equals(0, consumed)
			assert.is_string(err)
		end)

		it("reports a protocol error for invalid UTF-8 in a text frame", function()
			local payload = "\xC0\x00"
			local data = string.char(0x81) .. string.char(#payload) .. payload
			local parsed, consumed, err = frame.parse_frame(data)
			assert.is_nil(parsed)
			assert.equals(0, consumed)
			assert.is_string(err)
		end)

		it("does not UTF-8 validate a non-final text frame (codepoint may span frames)", function()
			-- "\xC3" is the first byte of a two-byte UTF-8 sequence; invalid on its own.
			local data = frame.create_frame(frame.OPCODE.TEXT, "\xC3", false, true)
			local parsed, _, err = frame.parse_frame(data)
			assert.is_not_nil(parsed)
			assert.is_nil(err)
			assert.is_false(parsed.fin)
		end)
	end)

	describe("is_control_frame", function()
		it("returns true for close", function()
			assert.is_true(frame.is_control_frame(frame.OPCODE.CLOSE))
		end)

		it("returns true for ping", function()
			assert.is_true(frame.is_control_frame(frame.OPCODE.PING))
		end)

		it("returns true for pong", function()
			assert.is_true(frame.is_control_frame(frame.OPCODE.PONG))
		end)

		it("returns false for text", function()
			assert.is_false(frame.is_control_frame(frame.OPCODE.TEXT))
		end)

		it("returns false for binary", function()
			assert.is_false(frame.is_control_frame(frame.OPCODE.BINARY))
		end)
	end)
end)
