local statusline = require("claude-transport.statusline")

describe("statusline", function()
	describe("get", function()
		it("returns a table with expected keys", function()
			local result = statusline.get()
			assert.is_boolean(result.running)
			assert.is_boolean(result.connected)
			assert.is_number(result.client_count)
		end)
	end)

	describe("is_connected", function()
		it("returns a boolean", function()
			assert.is_boolean(statusline.is_connected())
		end)
	end)

	describe("text", function()
		it("returns a string", function()
			assert.is_string(statusline.text())
		end)

		it("shows 'off' when not running", function()
			local result = statusline.text()
			assert.matches("off", result:lower())
		end)
	end)

	describe("icon", function()
		it("returns table with icon and color", function()
			local result = statusline.icon()
			assert.is_string(result.icon)
			assert.is_string(result.color)
		end)
	end)
end)
